import mongoose from "mongoose";

const arrayLimit = (val) => {
  return val.length <= 4;
};
const productSchema = new mongoose.Schema(
  {
    id: {
      type: Schema.Types.ObjectId,
      auto: true, // id is automatically generated by MongoDB
    },
    user_id: {
      type: Schema.Types.ObjectId,
      ref: "User", // Reference to the User model
      required: true,
    },
    name: {
      type: String,
      required: true,
      trim: true, // Trims whitespace from the start and end of the string
    },
    image: {
      type: String,
      required: true,
    },
    photos: {
      type: [String], // Array of strings to store photo URLs
      validate: [arrayLimit, "Exceeds the limit of 4 photos"],
    },
    description: {
      type: String,
      required: true,
      trim: true,
    },
    price: {
      type: Number,
      required: true,
      min: 0, // Ensures price is not negative
    },
    pickup_point: {
      type: String,
      required: true,
      trim: true,
    },
    category_id: {
      type: Schema.Types.ObjectId,
      ref: "Category", // Reference to the Category model
      required: true,
    },
    stock_quantity: {
      type: Number,
      required: true,
      min: 0,
      default: 0,
    },
    status: {
      type: String,
      enum: ["processing", "active", "sold"],
      default: "processing",
    },

    deleted_at: {
      type: Date,
      default: null,
    },
  },
  {
    timestamps: { createdAt: "created_at", updatedAt: "updated_at" }, // Automatically add created_at and updated_at
  }
);

const Product = mongoose.model("Product", productSchema);

export default Product;
